### ISSUE TITLE
Can't resolve '../../node_modules/caver-js/packages/caver-account/src/accountKey/accountKeyHelper'

### ISSUE THREAD

**Issue by jungsunwoung** [ground-x/caver-js-ext-kas#63]
**Describe the bug**
caver-js-ext-kas를 사용하고 있는데 원래 v 1.0.0에서는 문제없이 작동하다가 이번에 v 1.0.2로 업데이트 하면서 문제가 발생했습니다.
Can't resolve '../../node_modules/caver-js/packages/caver-account/src/accountKey/accountKeyHelper' in '/Users/[username]/Documents/GitHub/ydot/frontend/ydot/node_modules/caver-js-ext-kas/src/wallet'

다음과 같은 에러가 발생했고 \Could not find a declaration file for module 'caver-js-ext-kas'. 와 같은 에러가 CaverExtKAS를 import하는 과정에서 생겼습니다.

**Attachments**
If applicable, add data, logs or screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/51280827/102971784-55d0c900-453d-11eb-83d9-25e1c4ac3048.png)

**Environment (please complete the following information)**
 - caver-js-ext-kas version or git revision that exhibits the issue 
 v1.0.2
node -> 10과 12 다 테스트 해봤는데 안됩니다.

**Additional context**

**Comment by kjhman21** [comment]
https://forum.klaytn.com/t/kas-1-0-2-module-not-found/566

클레이튼 포럼에서 답변되었습니다.
